apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
data:
  MONGODB_DATABASE: {{ .Values.config.database | quote }}
  MONGODB_PORT_NUMBER: {{ .Values.service.port.api | quote }}
  MONGODB_REPLICA_SET_KEY: {{ .Values.config.replicaSet.key | quote }}
