apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-dump
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: dump
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.job.dump.schedule | quote }}
  suspend: {{ .Values.job.dump.suspend }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
            {{- with merge .Values.job.dump.podAnnotations .Values.global.annotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ include "edusharing_common_lib.names.name" . }}-job-dump
            image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.job.dump.image.name }}:{{ .Values.job.dump.image.tag }}
            imagePullPolicy: {{ .Values.global.image.pullPolicy }}
            args:
            - "/bin/bash"
            - "-ec"
            - |
              mongodump --uri={{ printf "mongodb://%s-0:%d,%s-1:%d,%s-2:%d/%s" (include "edusharing_common_lib.names.name" .) (.Values.service.port.api | int) (include "edusharing_common_lib.names.name" .) (.Values.service.port.api | int) (include "edusharing_common_lib.names.name" .) (.Values.service.port.api | int) .Values.config.database }} --archive --gzip -u ${MONGODB_ROOT_USER} -p ${MONGODB_ROOT_PASSWORD} > /bitnami/mongodb/dump-$(date +'%H%M').gz
            envFrom:
            - configMapRef:
                name: {{ include "edusharing_common_lib.names.name" . }}-env
            - secretRef:
                name: {{ include "edusharing_common_lib.names.name" . }}-env
            volumeMounts:
            - name: share-data
              mountPath: /bitnami/mongodb
            {{- with .Values.job.dump.startupProbe }}
            startupProbe:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo startupProbe > /dev/null"
              failureThreshold: {{ .failureThreshold }}
              initialDelaySeconds: {{ .initialDelaySeconds }}
              periodSeconds: {{ .periodSeconds }}
              successThreshold: {{ .successThreshold }}
              timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- with .Values.job.dump.livenessProbe }}
            livenessProbe:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo livenessProbe > /dev/null"
              failureThreshold: {{ .failureThreshold }}
              initialDelaySeconds: {{ .initialDelaySeconds }}
              periodSeconds: {{ .periodSeconds }}
              timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- with .Values.job.dump.readinessProbe }}
            readinessProbe:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo readinessProbe > /dev/null"
              failureThreshold: {{ .failureThreshold }}
              initialDelaySeconds: {{ .initialDelaySeconds }}
              periodSeconds: {{ .periodSeconds }}
              successThreshold: {{ .successThreshold }}
              timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- with .Values.job.dump.resources }}
            resources: {{ toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.job.dump.securityContext }}
            securityContext: {{ toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.global.image.pullSecrets }}
          imagePullSecrets: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with merge .Values.podSecurityContext .Values.global.security }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.terminationGracePeriod }}
          terminationGracePeriodSeconds: {{ . }}
          {{- end }}
          {{- with .Values.nodeAffinity }}
          affinity:
            nodeAffinity: {{ toYaml . | nindent 14 }}
          {{- end }}
          volumes:
          - name: share-data
            {{ tpl .Values.persistence.share.data.type . | nindent 12 }}
