apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
type: Opaque
data:
  MONGODB_USERNAME: {{ .Values.config.username | b64enc | quote }}
  MONGODB_PASSWORD: {{ default .Values.global.password .Values.config.password | b64enc | quote }}
  MONGODB_ROOT_USER: {{ .Values.config.username | b64enc | quote }}
  MONGODB_ROOT_PASSWORD: {{ default .Values.global.password .Values.config.password | b64enc | quote }}
