{{- if .Values.global.cluster.istio.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
{{- range $i, $e := until (.Values.replicaCount | int) }}
{{- $targetPod := (printf "%s-%d" (include "edusharing_repository_mongo.name" $) $i) }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $targetPod }}
  labels: {{ include "edusharing_repository_mongo.labels.app" $ | nindent 4 }}
spec:
  hosts:
  - {{ include "edusharing_repository_mongo.name" $ }}
  http:
  - route:
    - destination:
        host: {{ $targetPod }}
      weight: 100
{{- end }}
{{- end }}
{{- end }}
