variables:
  COMMON_BIND_HOST: "0.0.0.0"
  DEPLOY_DOCKER_HELM: "true"
  DEPLOY_TIMESTAMP: "$DEPLOY_TIMESTAMP"
  DOCKER_DRIVER: "$DIND_DRIVER"
  DOCKER_HOST: "$DIND_HOST"
  DOCKER_TLS_CERTDIR: "$DIND_TLS_CERTDIR"
  MAVEN_CLI: "-Ddocker.registry=$DOCKER_REGISTRY -Dhelm.deploy.url=$HELM_REGISTRY -Dhelm.deploy.type=$HELM_TYPE -Dmaven.deploy.releases=$MAVEN_DEPLOY_RELEASES -Dmaven.deploy.snapshots=$MAVEN_DEPLOY_SNAPSHOTS --batch-mode --errors --fail-fast --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  image: maven:3.8.4-eclipse-temurin-17
  services:
    - name: "$DIND_IMAGE"
      alias: docker
      entrypoint: [ "env", "-u", "DOCKER_HOST" ]
      command: [ "dockerd-entrypoint.sh" ]

stages:
  - lint
  - deploy

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^maven\/release\/.*/ && $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_BRANCH !~ /^maven\/release\/.*/ && $CI_COMMIT_TAG == null
  artifacts:
    paths:
      - Backend/services/module/target/surefire-reports
    when: on_failure
    expire_in: 3 day
  script:
    - mvn $MAVEN_CLI -s .mvn/settings.xml deploy

check-helmreadme:
  stage: lint
  image: node:lts-alpine3.20
  before_script:
    - ln -s $CI_PROJECT_DIR/deploy/docker/helm/src/main/chart /tmp/deploy && cp /tmp/deploy/README.md /tmp/README_deploy.md
  script:
    - wget -qO- https://github.com/bitnami/readme-generator-for-helm/archive/refs/tags/2.6.1.tar.gz | tar -xz -C /tmp
    - cd /tmp; npm install ./readme-generator-for-helm-2.6.1; cd readme-generator-for-helm-2.6.1
    - ./bin/index.js -v /tmp/deploy/values.yaml -r /tmp/README_deploy.md
    - diff /tmp/README_deploy.md /tmp/deploy/README.md     || (echo "README was not generated before committing." && exit 1)

