version: '3.7'

services:

  mongo-database:
    environment:
      MONGODB_EXTRA_REPOSITORY_DATABASE: "${REPOSITORY_MONGO_DATABASE:-repository}"
      MONGODB_EXTRA_REPOSITORY_USERNAME: "${REPOSITORY_MONGO_USER:-repository}"
      MONGODB_EXTRA_REPOSITORY_PASSWORD: "${REPOSITORY_MONGO_PASS:-repository}"

  repository-service:
    environment:
      REPOSITORY_MONGO_DATABASE: "${REPOSITORY_MONGO_DATABASE:-repository}"
      REPOSITORY_MONGO_CONNECTION_STRING: "${REPOSITORY_MONGO_CONNECTION_STRING:-mongodb://${REPOSITORY_MONGO_USER:-repository}:${REPOSITORY_MONGO_PASS:-repository}@mongo-database:27017/${REPOSITORY_MONGO_DATABASE:-repository}?authSource=${REPOSITORY_MONGO_DATABASE:-repository}}"
    depends_on:
      - mongo-database
