version: '3.7'

services:

  repository-mongo-primary:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_MONGO_PORT:-8500}:27017"

  repository-mongo-secondary:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:8502:27017"

  repository-mongo-arbiter:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:8503:27017"

  repository-mongo-express:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_MONGO_EXPRESS_PORT:-8501}:8081"
