version: '3.7'

services:

  repository-mongo:
    image: "${docker.repository}/edu_sharing-community-repository-plugin-mongo-deploy-docker-build-mongo:${docker.tag}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${REPOSITORY_MONGO_USER:-repository}"
      MONGO_INITDB_ROOT_PASSWORD: "${REPOSITORY_MONGO_PASS:-repository}"
    expose:
      - "27017"
    volumes:
      - "repository-mongo-volume-data:/data/db"

  repository-mongo-express:
    image: "${docker.repository}/edu_sharing-community-repository-plugin-mongo-deploy-docker-build-mongo_express:${docker.tag}"
    environment:
      ME_CONFIG_MONGODB_SERVER: "repository-mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${REPOSITORY_MONGO_USER:-repository}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${REPOSITORY_MONGO_PASS:-repository}"
      ME_CONFIG_MONGODB_URL: "mongodb://${REPOSITORY_MONGO_USER:-repository}:${REPOSITORY_MONGO_PASS:-repository}@repository-mongo:27017/"
    expose:
      - "8081"
    depends_on:
      - repository-mongo

  repository-service:
    environment:
      REPOSITORY_MONGO_PROTOCOL: "mongodb"
      REPOSITORY_MONGO_HOST: "repository-mongo"
      REPOSITORY_MONGO_PORT: "27017"
      REPOSITORY_MONGO_USER: "${REPOSITORY_MONGO_USER:-repository}"
      REPOSITORY_MONGO_PASS: "${REPOSITORY_MONGO_PASS:-repository}"
      REPOSITORY_MONGO_DATABASE: "${REPOSITORY_MONGO_DATABASE:-edu-sharing}"

    depends_on:
      - repository-mongo

volumes:
  repository-mongo-volume-data: