version: '3.7'

services:

  repository-mongo:
    image: "${docker.repository}/${docker.prefix}-deploy-installer-scripts-debian-bullseye:${docker.tag}"
    expose:
      - 27017
    depends_on:
      - repository

  repository:
    environment:
      REPOSITORY_MONGO_HOST: "repository-mongo"
      REPOSITORY_MONGO_PORT: "27017"
