version: '3.7'

services:

  repository-mongo:
    image: "${docker.repository}/${docker.prefix}-deploy-installer-mongodb-scripts-debian-bullseye:${docker.tag}"
    tty: true
    expose:
      - 27017

  repository:
    environment:
      REPOSITORY_MONGO_CONNECTION_STRING: "mongodb://repository:repository@127.0.0.1:27017/edu-sharing"
