version: '3.7'

services:

  repository-elastic:
    image: "${docker.registry}/${docker.repository}/edu_sharing-community-repository-plugin-elastic-deploy-installer-tracker-scripts-debian-bullseye:${docker.tag}"
