mongo: {
  connectionString: "mongodb://repository:repository@repository-mongo:27017",
  database: "edu-sharing",
}

repository: {
  mongoDataTracking: {
    expireAfter: 30d
  }
}

jobs.entries += {
  name: "Delete obsolete MongoDB documents job",
  class: "org.edu_sharing.plugin_mongo.jobs.quarz.ObsoleteMongoEntriesDeletionJob",
  trigger: "Cron[0 0 1 * * ?]", // fire at 1 am everyday
  params: {
    "maxDeletedNodeChecks": 5000,
    "maxTransactionResults": 5000,
  }
}

jobs.entries += {
  name: "Retrying operations on failed or missing MongoDB Alfresco operation logs.",
  class: "org.edu_sharing.plugin_mongo.jobs.quarz.RetryFailedOrMissingMongoAlfOpLogJob",
  trigger: "Cron[0 */6 * * * ?]", // fire every 6 hours
  params: {
    "minTimeOffset": 216000000, // 6 hours offset
  }
}
