########################################################################################################################
# GLOBAL
########################################################################################################################

## @section Global parameters
global:

  ## @param global.annotations Define global annotations
  annotations: {}

  cluster:

    ## @param global.cluster.domain Set global cluster domain
    domain: cluster.local

    istio:
      ## @param global.cluster.istio.enabled Enable Istio Service mesh
      enabled: false

    pdb:
      ## @param global.cluster.pdb.enabled Enable PDB
      enabled: false

    storage:
      data:
        ## @param global.cluster.storage.data.permission Enable global custom data storage permissions
        permission: false
        ## @param global.cluster.storage.data.spec Set data storage spec
        spec: {}
      share:
        ## @param global.cluster.storage.share.permission Enable global custom share storage permissions
        permission: false
        ## @param global.cluster.storage.share.spec Set share storage spec
        spec: {}

  ## @param global.debug Enable global debugging
  debug: false

  image:
    ## @param global.image.pullPolicy Set global image pullPolicy
    pullPolicy: Always
    ## @param global.image.pullSecrets Set global image pullSecrets
    pullSecrets: []
    ## @param global.image.registry Set global image container registry
    registry: ${docker.registry}
    ## @param global.image.repository Set global image container repository
    repository: ${docker.repository}
    ## @param global.image.common Set global image container common
    common: ${docker.common}

  metrics:
    scrape:
      ## @param global.metrics.scrape.interval Set prometheus scrape interval
      interval: 60s
      ## @param global.metrics.scrape.timeout Set prometheus scrape timeout
      timeout: 60s
    servicemonitor:
      ## @param global.metrics.servicemonitor.enabled Enable metrics service monitor
      enabled: false

  ## @param global.password Set global password
  password: ""

  ## @param global.security Set global security parameters
  security: {}

########################################################################################################################
# LOCAL
########################################################################################################################

## @section Local parameters
## @param nameOverride Override name
nameOverride: edusharing-repository-mongo

image:
  ## @param image.name Set image name
  name: ${docker.edu_sharing.community.common.mongodb.name}
  ## @param image.tag Set image tag
  tag: ${docker.edu_sharing.community.common.mongodb.tag}

########################################################################################################################

## @param replicaCount Define amount of parallel replicas to run
replicaCount: 3

########################################################################################################################

service:

  port:
    ## @param service.port.api Set port for service API
    api: 27017
    ## @param service.port.metrics Set port for metrics
    metrics: 9216

config:
  ## @param config.database Set database for mongo service
  database: repository
  ## @param config.username Set username for mongo service
  username: repository
  ## @param config.password Set password for mongo service
  password: ""

  replicaSet:
    ## @param config.replicaSet.key Set replicaSet key for service
    key: "repository"

  ## @param config.override Set custom overrides
  override: {}

########################################################################################################################

## @param debug Enable debugging
debug: false

########################################################################################################################

## @param nodeAffinity Set node affinity
nodeAffinity: {}
## @param podAntiAffinity Set pod antiaffinity
podAntiAffinity: "soft"

## @param tolerations Set tolerations
tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      ## @param persistence.data.spec.accessModes Set access modes for persistent data
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          ## @param persistence.data.spec.resources.requests.storage Set storage request for persistent data
          storage: 5Gi
  share:
    data:
      ## @param persistence.share.data.create Create persistent data share
      create: true
      ## @param persistence.share.data.type Set volume type of data share
      type: |
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_mongo.pvc.share.data" . }}
      spec:
        ## @param persistence.share.data.spec.accessModes Set access modes for persistent data share
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            ## @param persistence.share.data.spec.resources.requests.storage Set storage request for persistent data share
            storage: 5Gi

########################################################################################################################

## @param podAnnotations Set custom pod annotations
podAnnotations: {}

podSecurityContext:
  ## @param podSecurityContext.fsGroup Set fs group for access
  fsGroup: 1000
  ## @param podSecurityContext.fsGroupChangePolicy Set change policy for fs group
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  ## @param securityContext.allowPrivilegeEscalation Allow privilege escalation
  allowPrivilegeEscalation: false
  capabilities:
    ## @param securityContext.capabilities.drop Set drop capabilities
    drop:
      - ALL
  ## @param securityContext.runAsUser Define user to run under
  runAsUser: 1000

########################################################################################################################

## @param terminationGracePeriod Define grace period for termination
terminationGracePeriod: 120

startupProbe:
  ## @param startupProbe.failureThreshold Failure threshold for startupProbe
  failureThreshold: 30
  ## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  initialDelaySeconds: 0
  ## @param startupProbe.periodSeconds Period seconds for startupProbe
  periodSeconds: 20
  ## @param startupProbe.successThreshold Success threshold for startupProbe
  successThreshold: 1
  ## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
  timeoutSeconds: 10

livenessProbe:
  ## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
  failureThreshold: 3
  ## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  initialDelaySeconds: 30
  ## @param livenessProbe.periodSeconds Period seconds for livenessProbe
  periodSeconds: 30
  ## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  timeoutSeconds: 10

readinessProbe:
  ## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
  failureThreshold: 1
  ## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  initialDelaySeconds: 10
  ## @param readinessProbe.periodSeconds Period seconds for readinessProbe
  periodSeconds: 10
  ## @param readinessProbe.successThreshold Set threshold for success on readiness probe
  successThreshold: 1
  ## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    ## @param resources.limits.cpu Set CPU limit on resources
    cpu: 500m
    ## @param resources.limits.memory Set memory limit on resources
    memory: 2Gi
  requests:
    ## @param resources.requests.cpu Set CPU for requests on resources
    cpu: 500m
    ## @param resources.requests.memory Set memory for requests on resources
    memory: 2Gi

########################################################################################################################

init:

  permission:

    image:
      ## @param init.permission.image.name Set init container image name
      name: ${docker.edu_sharing.community.common.minideb.name}
      ## @param init.permission.image.tag Set init container image tag
      tag: "${docker.edu_sharing.community.common.minideb.tag}"

    ## @param init.permission.startupProbe Optional specs for startupProbe
    startupProbe:

    ## @param init.permission.livenessProbe Optional specs for livenessProbe
    livenessProbe:

    ## @param init.permission.readinessProbe Optional specs for readinessProbe
    readinessProbe:

    resources:
      limits:
        ## @param init.permission.resources.limits.cpu Set init container CPU limit on resources
        cpu: 125m
        ## @param init.permission.resources.limits.memory Set init container memory limit on resources
        memory: 512Mi
      requests:
        ## @param init.permission.resources.requests.cpu Set init container CPU for requests on resources
        cpu: 125m
        ## @param init.permission.resources.requests.memory Set init container memory for requests on resources
        memory: 512Mi

    securityContext:
      ## @param init.permission.securityContext.runAsUser Set user to run init container under
      runAsUser: 0

########################################################################################################################

job:

  dump:

    image:
      ## @param job.dump.image.name Set dump job image name
      name: ${docker.edu_sharing.community.common.mongodb.name}
      ## @param job.dump.image.tag Set dump job image tag
      tag: ${docker.edu_sharing.community.common.mongodb.tag}

    ## @param job.dump.podAnnotations Set dump job pod annotations
    podAnnotations: {}

    ## @param job.dump.startupProbe Optional specs for startupProbe
    startupProbe:

    ## @param job.dump.livenessProbe Optional specs for livenessProbe
    livenessProbe:

    ## @param job.dump.readinessProbe Optional specs for readinessProbe
    readinessProbe:

    resources:

      limits:
        ## @param job.dump.resources.limits.cpu Set CPU limit on resources
        cpu: 500m
        ## @param job.dump.resources.limits.memory Set memory limit on resources
        memory: 2Gi
      requests:
        ## @param job.dump.resources.requests.cpu Set CPU for requests on resources
        cpu: 500m
        ## @param job.dump.resources.requests.memory Set memory for requests on resources
        memory: 2Gi

    ## @param job.dump.schedule Set cron-like dump job schedule
    schedule: "0 * * * *"
    ## @param job.dump.suspend Suspend dump job
    suspend: false

    securityContext:

      ## @param job.dump.securityContext.allowPrivilegeEscalation Allow privilege escalation
      allowPrivilegeEscalation: false
      capabilities:
        ## @param job.dump.securityContext.capabilities.drop Set drop capabilities
        drop:
          - ALL
      ## @param job.dump.securityContext.runAsUser Define user to run under
      runAsUser: 1000

########################################################################################################################

sidecar:

  metrics:
    ## @param sidecar.metrics.enabled Enable metrics sidecar
    enabled: true

    image:
      ## @param sidecar.metrics.image.name Set metrics sidecar image name
      name: ${docker.edu_sharing.community.common.mongodb.exporter.name}
      ## @param sidecar.metrics.image.tag Set metrics sidecar image tag
      tag: "${docker.edu_sharing.community.common.mongodb.exporter.tag}"

    ## @param sidecar.metrics.relabelings Set metrics sidecar relabelings
    relabelings: []

    ## @param sidecar.metrics.startupProbe Optional specs for startupProbe
    startupProbe:

    ## @param sidecar.metrics.livenessProbe Optional specs for livenessProbe
    livenessProbe:

    ## @param sidecar.metrics.readinessProbe Optional specs for readinessProbe
    readinessProbe:

    resources:

      limits:
        ## @param sidecar.metrics.resources.limits.cpu Set CPU limit on resources
        cpu: 125m
        ## @param sidecar.metrics.resources.limits.memory Set memory limit on resources
        memory: 512Mi
      requests:
        ## @param sidecar.metrics.resources.requests.cpu Set CPU for requests on resources
        cpu: 125m
        ## @param sidecar.metrics.resources.requests.memory Set memory for requests on resources
        memory: 512Mi

    securityContext:

      ## @param sidecar.metrics.securityContext.allowPrivilegeEscalation Allow privilege escalation
      allowPrivilegeEscalation: false
      capabilities:
        ## @param sidecar.metrics.securityContext.capabilities.drop Set drop capabilities
        drop:
          - ALL
      ## @param sidecar.metrics.securityContext.runAsUser Define user to run under
      runAsUser: 1000

########################################################################################################################
